import { Components } from './components'

export type BaseHTMLElement<T extends Components = Components> = T extends
  | 'Button'
  | 'IconButton'
  | 'TextDropdownButton'
  ? 'button'
  : T extends 'Icon'
  ? 'svg'
  : T extends 'Paragraph'
  ? 'p'
  : T extends 'Link'
  ? 'a'
  : T extends 'Text' | 'Tab'
  ? 'span'
  : T extends 'Checkbox' | 'Input'
  ? 'input'
  : T extends 'Label'
  ? 'label'
  : 'div'
