name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install docs dependencies
        working-directory: './docs'
        run: 'yarn install --frozen-lockfile'
      - name: Run build
        run: yarn run build
      - name: Run prettier
        run: yarn run prettier 'src/**/*.js' --check
      - name: Run test
        run: yarn run test
      - name: Run docs lint
        working-directory: './docs'
        run: yarn run lint
      - name: Run size-limit
        run: yarn run size-limit
